### PR TITLE
Fix configuration regarding different LED types (RGB, BRG, GRB etc.)

### PR DESCRIPTION
**Pull request by ATho95**
The LED configuration as it is does not work for RGB and GRB Led strips. I wrote the ColorFeature NeoMultiFeature Class which replaces all NeoBrgFeature, NeoRgbFeature etc.
The code is tested for RGB and GRB Leds.
I removed the reset when the Colortype has changed to Grbw but let the code in as a comment.
Depending on the command mode a Red/Green/Blue icon is displayed till the next minute change to check the color type.

### CODE REVIEW

**Comment by ATho95** [comment]
Btw. I removed my old fork and forked a new one because the ESPWortuhr:main had disappeared

**Comment by ATho95** [comment]
Ups, clicked on "Close" at the end of the PR mistakenly in the opinion to complete the pull request

**Comment by dbambus** [comment]
That's a lot of changed lines. It will take till the weekend till I can review that.

What do you tink about having HSL Colors internaly and just switching them in the very last step to RGB to set them ?

**Comment by ATho95** [comment]
> What do you tink about having HSL Colors internaly and just switching them in the very last step to RGB to set them ?

The HSL struct consists of 3 floats or 12 bytes, RGB occupies only 3 Bytes.
A lot of code must be changed.
I would keep RGB

**Review by dbambus — APPROVED** [review]

**Pull request merged**
