### PR TITLE
Use Colorwheel for color selection

### PR DESCRIPTION
**Pull request by tali**
Replace the custom RGB(W) sliders with an iro.js color wheel.
For RGBW LEDs, the alpha channel is used to control the white LED.

Foreground and background colors can be selected in the same color
picker next to each other.
A checkbox is added to quickly enable/disable the background color.

### CODE REVIEW

**Comment by dbambus** [comment]
I didn't checked the color picker in detail, but is it possible to set it up to transfer HSL colors instead of RGBA colors ? HSL colors are more accurate regarding the White channel.

Also the payload would be smaller.

**Comment by tali** [comment]
Yeah, using HSL instead of RGB is the next step I want to tackle. This would also allow to calibrate the RGB colors to better match the colors on the web interface.

**Comment by tali** [comment]
The screenshot referenced by the README also has to be updated.

**Comment by dbambus** [comment]
> The screenshot referenced by the README also has to be updated.

I couldn't find it in your repo or the commit ? To review the pull request i would test it on my Clock before. 

HSL would also mean a better way to use RGBW in the whole code, since it will be converted in the NeoPixelBus Lib completely and we only have to set HSLColor objects as attributes to the strip.

**Review by dbambus — APPROVED** [review]

**Pull request merged**
